/*
 * Unit Python SDK
 * An API for testing openapi-python-client for unit-sdk
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.ApplicationFormAttributes;
import io.swagger.client.model.Relationships1;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * ApplicationForm
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-03-26T12:59:56.018830800+03:00[Asia/Jerusalem]")
public class ApplicationForm {
  @SerializedName("type")
  private String type = null;

  @SerializedName("id")
  private String id = null;

  @SerializedName("attributes")
  private ApplicationFormAttributes attributes = null;

  @SerializedName("relationships")
  private Relationships1 relationships = null;

  @SerializedName("officerIsBeneficialOwner")
  private Boolean officerIsBeneficialOwner = false;

  public ApplicationForm type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @Schema(required = true, description = "")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public ApplicationForm id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(required = true, description = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public ApplicationForm attributes(ApplicationFormAttributes attributes) {
    this.attributes = attributes;
    return this;
  }

   /**
   * Get attributes
   * @return attributes
  **/
  @Schema(required = true, description = "")
  public ApplicationFormAttributes getAttributes() {
    return attributes;
  }

  public void setAttributes(ApplicationFormAttributes attributes) {
    this.attributes = attributes;
  }

  public ApplicationForm relationships(Relationships1 relationships) {
    this.relationships = relationships;
    return this;
  }

   /**
   * Get relationships
   * @return relationships
  **/
  @Schema(description = "")
  public Relationships1 getRelationships() {
    return relationships;
  }

  public void setRelationships(Relationships1 relationships) {
    this.relationships = relationships;
  }

  public ApplicationForm officerIsBeneficialOwner(Boolean officerIsBeneficialOwner) {
    this.officerIsBeneficialOwner = officerIsBeneficialOwner;
    return this;
  }

   /**
   * Get officerIsBeneficialOwner
   * @return officerIsBeneficialOwner
  **/
  @Schema(description = "")
  public Boolean isOfficerIsBeneficialOwner() {
    return officerIsBeneficialOwner;
  }

  public void setOfficerIsBeneficialOwner(Boolean officerIsBeneficialOwner) {
    this.officerIsBeneficialOwner = officerIsBeneficialOwner;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ApplicationForm applicationForm = (ApplicationForm) o;
    return Objects.equals(this.type, applicationForm.type) &&
        Objects.equals(this.id, applicationForm.id) &&
        Objects.equals(this.attributes, applicationForm.attributes) &&
        Objects.equals(this.relationships, applicationForm.relationships) &&
        Objects.equals(this.officerIsBeneficialOwner, applicationForm.officerIsBeneficialOwner);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, id, attributes, relationships, officerIsBeneficialOwner);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ApplicationForm {\n");
    
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    attributes: ").append(toIndentedString(attributes)).append("\n");
    sb.append("    relationships: ").append(toIndentedString(relationships)).append("\n");
    sb.append("    officerIsBeneficialOwner: ").append(toIndentedString(officerIsBeneficialOwner)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
