/*
 * Unit Python SDK
 * An API for testing openapi-python-client for unit-sdk
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.annotations.SerializedName;
import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets applicationStatus
 */
@JsonAdapter(ApplicationStatus.Adapter.class)
public enum ApplicationStatus {
  AWAITINGDOCUMENTS("AwaitingDocuments"),
  PENDINGREVIEW("PendingReview"),
  APPROVED("Approved"),
  DENIED("Denied"),
  PENDING("Pending"),
  CANCELED("Canceled");

  private String value;

  ApplicationStatus(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static ApplicationStatus fromValue(String input) {
    for (ApplicationStatus b : ApplicationStatus.values()) {
      if (b.value.equals(input)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<ApplicationStatus> {
    @Override
    public void write(final JsonWriter jsonWriter, final ApplicationStatus enumeration) throws IOException {
      jsonWriter.value(String.valueOf(enumeration.getValue()));
    }

    @Override
    public ApplicationStatus read(final JsonReader jsonReader) throws IOException {
      Object value = jsonReader.nextString();
      return ApplicationStatus.fromValue((String)(value));
    }
  }
}
