/*
 * Unit Python SDK
 * An API for testing openapi-python-client for unit-sdk
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.Address;
import io.swagger.client.model.DeviceFingerprint;
import io.swagger.client.model.EvaluationParams;
import io.swagger.client.model.FullName;
import io.swagger.client.model.Industry;
import io.swagger.client.model.JwtSubject;
import io.swagger.client.model.Phone;
import io.swagger.client.model.PowerOfAttorneyAgent1;
import io.swagger.client.model.Tags;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.threeten.bp.LocalDate;
/**
 * CreateIndividualApplicationAttributes
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-03-26T12:59:56.018830800+03:00[Asia/Jerusalem]")
public class CreateIndividualApplicationAttributes {
  @SerializedName("fullName")
  private FullName fullName = null;

  @SerializedName("email")
  private String email = null;

  @SerializedName("phone")
  private Phone phone = null;

  @SerializedName("ssn")
  private Object ssn = null;

  @SerializedName("passport")
  private Object passport = null;

  @SerializedName("nationality")
  private String nationality = null;

  @SerializedName("matriculaConsular")
  private String matriculaConsular = null;

  @SerializedName("address")
  private Address address = null;

  @SerializedName("dateOfBirth")
  private LocalDate dateOfBirth = null;

  @SerializedName("dba")
  private Object dba = null;

  @SerializedName("ein")
  private Object ein = null;

  @SerializedName("ip")
  private OneOfCreateIndividualApplicationAttributesIp ip = null;

  @SerializedName("soleProprietorship")
  private Boolean soleProprietorship = false;

  @SerializedName("tags")
  private Tags tags = null;

  @SerializedName("idempotencyKey")
  private String idempotencyKey = null;

  @SerializedName("deviceFingerprints")
  private List<DeviceFingerprint> deviceFingerprints = null;

  @SerializedName("jwtSubject")
  private JwtSubject jwtSubject = null;

  @SerializedName("powerOfAttorneyAgent")
  private PowerOfAttorneyAgent1 powerOfAttorneyAgent = null;

  @SerializedName("industry")
  private Industry industry = null;

  @SerializedName("evaluationParams")
  private EvaluationParams evaluationParams = null;

  public CreateIndividualApplicationAttributes fullName(FullName fullName) {
    this.fullName = fullName;
    return this;
  }

   /**
   * Get fullName
   * @return fullName
  **/
  @Schema(required = true, description = "")
  public FullName getFullName() {
    return fullName;
  }

  public void setFullName(FullName fullName) {
    this.fullName = fullName;
  }

  public CreateIndividualApplicationAttributes email(String email) {
    this.email = email;
    return this;
  }

   /**
   * Get email
   * @return email
  **/
  @Schema(required = true, description = "")
  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public CreateIndividualApplicationAttributes phone(Phone phone) {
    this.phone = phone;
    return this;
  }

   /**
   * Get phone
   * @return phone
  **/
  @Schema(required = true, description = "")
  public Phone getPhone() {
    return phone;
  }

  public void setPhone(Phone phone) {
    this.phone = phone;
  }

  public CreateIndividualApplicationAttributes ssn(Object ssn) {
    this.ssn = ssn;
    return this;
  }

   /**
   * Get ssn
   * @return ssn
  **/
  @Schema(description = "")
  public Object getSsn() {
    return ssn;
  }

  public void setSsn(Object ssn) {
    this.ssn = ssn;
  }

  public CreateIndividualApplicationAttributes passport(Object passport) {
    this.passport = passport;
    return this;
  }

   /**
   * Get passport
   * @return passport
  **/
  @Schema(description = "")
  public Object getPassport() {
    return passport;
  }

  public void setPassport(Object passport) {
    this.passport = passport;
  }

  public CreateIndividualApplicationAttributes nationality(String nationality) {
    this.nationality = nationality;
    return this;
  }

   /**
   * Get nationality
   * @return nationality
  **/
  @Schema(description = "")
  public String getNationality() {
    return nationality;
  }

  public void setNationality(String nationality) {
    this.nationality = nationality;
  }

  public CreateIndividualApplicationAttributes matriculaConsular(String matriculaConsular) {
    this.matriculaConsular = matriculaConsular;
    return this;
  }

   /**
   * Get matriculaConsular
   * @return matriculaConsular
  **/
  @Schema(description = "")
  public String getMatriculaConsular() {
    return matriculaConsular;
  }

  public void setMatriculaConsular(String matriculaConsular) {
    this.matriculaConsular = matriculaConsular;
  }

  public CreateIndividualApplicationAttributes address(Address address) {
    this.address = address;
    return this;
  }

   /**
   * Get address
   * @return address
  **/
  @Schema(required = true, description = "")
  public Address getAddress() {
    return address;
  }

  public void setAddress(Address address) {
    this.address = address;
  }

  public CreateIndividualApplicationAttributes dateOfBirth(LocalDate dateOfBirth) {
    this.dateOfBirth = dateOfBirth;
    return this;
  }

   /**
   * Get dateOfBirth
   * @return dateOfBirth
  **/
  @Schema(required = true, description = "")
  public LocalDate getDateOfBirth() {
    return dateOfBirth;
  }

  public void setDateOfBirth(LocalDate dateOfBirth) {
    this.dateOfBirth = dateOfBirth;
  }

  public CreateIndividualApplicationAttributes dba(Object dba) {
    this.dba = dba;
    return this;
  }

   /**
   * Get dba
   * @return dba
  **/
  @Schema(description = "")
  public Object getDba() {
    return dba;
  }

  public void setDba(Object dba) {
    this.dba = dba;
  }

  public CreateIndividualApplicationAttributes ein(Object ein) {
    this.ein = ein;
    return this;
  }

   /**
   * Get ein
   * @return ein
  **/
  @Schema(description = "")
  public Object getEin() {
    return ein;
  }

  public void setEin(Object ein) {
    this.ein = ein;
  }

  public CreateIndividualApplicationAttributes ip(OneOfCreateIndividualApplicationAttributesIp ip) {
    this.ip = ip;
    return this;
  }

   /**
   * Get ip
   * @return ip
  **/
  @Schema(description = "")
  public OneOfCreateIndividualApplicationAttributesIp getIp() {
    return ip;
  }

  public void setIp(OneOfCreateIndividualApplicationAttributesIp ip) {
    this.ip = ip;
  }

  public CreateIndividualApplicationAttributes soleProprietorship(Boolean soleProprietorship) {
    this.soleProprietorship = soleProprietorship;
    return this;
  }

   /**
   * Get soleProprietorship
   * @return soleProprietorship
  **/
  @Schema(description = "")
  public Boolean isSoleProprietorship() {
    return soleProprietorship;
  }

  public void setSoleProprietorship(Boolean soleProprietorship) {
    this.soleProprietorship = soleProprietorship;
  }

  public CreateIndividualApplicationAttributes tags(Tags tags) {
    this.tags = tags;
    return this;
  }

   /**
   * Get tags
   * @return tags
  **/
  @Schema(description = "")
  public Tags getTags() {
    return tags;
  }

  public void setTags(Tags tags) {
    this.tags = tags;
  }

  public CreateIndividualApplicationAttributes idempotencyKey(String idempotencyKey) {
    this.idempotencyKey = idempotencyKey;
    return this;
  }

   /**
   * Get idempotencyKey
   * @return idempotencyKey
  **/
  @Schema(description = "")
  public String getIdempotencyKey() {
    return idempotencyKey;
  }

  public void setIdempotencyKey(String idempotencyKey) {
    this.idempotencyKey = idempotencyKey;
  }

  public CreateIndividualApplicationAttributes deviceFingerprints(List<DeviceFingerprint> deviceFingerprints) {
    this.deviceFingerprints = deviceFingerprints;
    return this;
  }

  public CreateIndividualApplicationAttributes addDeviceFingerprintsItem(DeviceFingerprint deviceFingerprintsItem) {
    if (this.deviceFingerprints == null) {
      this.deviceFingerprints = new ArrayList<DeviceFingerprint>();
    }
    this.deviceFingerprints.add(deviceFingerprintsItem);
    return this;
  }

   /**
   * Get deviceFingerprints
   * @return deviceFingerprints
  **/
  @Schema(description = "")
  public List<DeviceFingerprint> getDeviceFingerprints() {
    return deviceFingerprints;
  }

  public void setDeviceFingerprints(List<DeviceFingerprint> deviceFingerprints) {
    this.deviceFingerprints = deviceFingerprints;
  }

  public CreateIndividualApplicationAttributes jwtSubject(JwtSubject jwtSubject) {
    this.jwtSubject = jwtSubject;
    return this;
  }

   /**
   * Get jwtSubject
   * @return jwtSubject
  **/
  @Schema(description = "")
  public JwtSubject getJwtSubject() {
    return jwtSubject;
  }

  public void setJwtSubject(JwtSubject jwtSubject) {
    this.jwtSubject = jwtSubject;
  }

  public CreateIndividualApplicationAttributes powerOfAttorneyAgent(PowerOfAttorneyAgent1 powerOfAttorneyAgent) {
    this.powerOfAttorneyAgent = powerOfAttorneyAgent;
    return this;
  }

   /**
   * Get powerOfAttorneyAgent
   * @return powerOfAttorneyAgent
  **/
  @Schema(description = "")
  public PowerOfAttorneyAgent1 getPowerOfAttorneyAgent() {
    return powerOfAttorneyAgent;
  }

  public void setPowerOfAttorneyAgent(PowerOfAttorneyAgent1 powerOfAttorneyAgent) {
    this.powerOfAttorneyAgent = powerOfAttorneyAgent;
  }

  public CreateIndividualApplicationAttributes industry(Industry industry) {
    this.industry = industry;
    return this;
  }

   /**
   * Get industry
   * @return industry
  **/
  @Schema(description = "")
  public Industry getIndustry() {
    return industry;
  }

  public void setIndustry(Industry industry) {
    this.industry = industry;
  }

  public CreateIndividualApplicationAttributes evaluationParams(EvaluationParams evaluationParams) {
    this.evaluationParams = evaluationParams;
    return this;
  }

   /**
   * Get evaluationParams
   * @return evaluationParams
  **/
  @Schema(description = "")
  public EvaluationParams getEvaluationParams() {
    return evaluationParams;
  }

  public void setEvaluationParams(EvaluationParams evaluationParams) {
    this.evaluationParams = evaluationParams;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateIndividualApplicationAttributes createIndividualApplicationAttributes = (CreateIndividualApplicationAttributes) o;
    return Objects.equals(this.fullName, createIndividualApplicationAttributes.fullName) &&
        Objects.equals(this.email, createIndividualApplicationAttributes.email) &&
        Objects.equals(this.phone, createIndividualApplicationAttributes.phone) &&
        Objects.equals(this.ssn, createIndividualApplicationAttributes.ssn) &&
        Objects.equals(this.passport, createIndividualApplicationAttributes.passport) &&
        Objects.equals(this.nationality, createIndividualApplicationAttributes.nationality) &&
        Objects.equals(this.matriculaConsular, createIndividualApplicationAttributes.matriculaConsular) &&
        Objects.equals(this.address, createIndividualApplicationAttributes.address) &&
        Objects.equals(this.dateOfBirth, createIndividualApplicationAttributes.dateOfBirth) &&
        Objects.equals(this.dba, createIndividualApplicationAttributes.dba) &&
        Objects.equals(this.ein, createIndividualApplicationAttributes.ein) &&
        Objects.equals(this.ip, createIndividualApplicationAttributes.ip) &&
        Objects.equals(this.soleProprietorship, createIndividualApplicationAttributes.soleProprietorship) &&
        Objects.equals(this.tags, createIndividualApplicationAttributes.tags) &&
        Objects.equals(this.idempotencyKey, createIndividualApplicationAttributes.idempotencyKey) &&
        Objects.equals(this.deviceFingerprints, createIndividualApplicationAttributes.deviceFingerprints) &&
        Objects.equals(this.jwtSubject, createIndividualApplicationAttributes.jwtSubject) &&
        Objects.equals(this.powerOfAttorneyAgent, createIndividualApplicationAttributes.powerOfAttorneyAgent) &&
        Objects.equals(this.industry, createIndividualApplicationAttributes.industry) &&
        Objects.equals(this.evaluationParams, createIndividualApplicationAttributes.evaluationParams);
  }

  @Override
  public int hashCode() {
    return Objects.hash(fullName, email, phone, ssn, passport, nationality, matriculaConsular, address, dateOfBirth, dba, ein, ip, soleProprietorship, tags, idempotencyKey, deviceFingerprints, jwtSubject, powerOfAttorneyAgent, industry, evaluationParams);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateIndividualApplicationAttributes {\n");
    
    sb.append("    fullName: ").append(toIndentedString(fullName)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    phone: ").append(toIndentedString(phone)).append("\n");
    sb.append("    ssn: ").append(toIndentedString(ssn)).append("\n");
    sb.append("    passport: ").append(toIndentedString(passport)).append("\n");
    sb.append("    nationality: ").append(toIndentedString(nationality)).append("\n");
    sb.append("    matriculaConsular: ").append(toIndentedString(matriculaConsular)).append("\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    dateOfBirth: ").append(toIndentedString(dateOfBirth)).append("\n");
    sb.append("    dba: ").append(toIndentedString(dba)).append("\n");
    sb.append("    ein: ").append(toIndentedString(ein)).append("\n");
    sb.append("    ip: ").append(toIndentedString(ip)).append("\n");
    sb.append("    soleProprietorship: ").append(toIndentedString(soleProprietorship)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("    idempotencyKey: ").append(toIndentedString(idempotencyKey)).append("\n");
    sb.append("    deviceFingerprints: ").append(toIndentedString(deviceFingerprints)).append("\n");
    sb.append("    jwtSubject: ").append(toIndentedString(jwtSubject)).append("\n");
    sb.append("    powerOfAttorneyAgent: ").append(toIndentedString(powerOfAttorneyAgent)).append("\n");
    sb.append("    industry: ").append(toIndentedString(industry)).append("\n");
    sb.append("    evaluationParams: ").append(toIndentedString(evaluationParams)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
