/*
 * Unit Python SDK
 * An API for testing openapi-python-client for unit-sdk
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.math.BigDecimal;
/**
 * DepositLimitsAttributesAchLimits
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-03-26T12:59:56.018830800+03:00[Asia/Jerusalem]")
public class DepositLimitsAttributesAchLimits {
  @SerializedName("dailyDebit")
  private BigDecimal dailyDebit = null;

  @SerializedName("dailyCredit")
  private BigDecimal dailyCredit = null;

  @SerializedName("monthlyDebit")
  private BigDecimal monthlyDebit = null;

  @SerializedName("monthlyDebitSoft")
  private BigDecimal monthlyDebitSoft = null;

  @SerializedName("dailyDebitSoft")
  private BigDecimal dailyDebitSoft = null;

  @SerializedName("monthlyCredit")
  private BigDecimal monthlyCredit = null;

  public DepositLimitsAttributesAchLimits dailyDebit(BigDecimal dailyDebit) {
    this.dailyDebit = dailyDebit;
    return this;
  }

   /**
   * Get dailyDebit
   * @return dailyDebit
  **/
  @Schema(required = true, description = "")
  public BigDecimal getDailyDebit() {
    return dailyDebit;
  }

  public void setDailyDebit(BigDecimal dailyDebit) {
    this.dailyDebit = dailyDebit;
  }

  public DepositLimitsAttributesAchLimits dailyCredit(BigDecimal dailyCredit) {
    this.dailyCredit = dailyCredit;
    return this;
  }

   /**
   * Get dailyCredit
   * @return dailyCredit
  **/
  @Schema(required = true, description = "")
  public BigDecimal getDailyCredit() {
    return dailyCredit;
  }

  public void setDailyCredit(BigDecimal dailyCredit) {
    this.dailyCredit = dailyCredit;
  }

  public DepositLimitsAttributesAchLimits monthlyDebit(BigDecimal monthlyDebit) {
    this.monthlyDebit = monthlyDebit;
    return this;
  }

   /**
   * Get monthlyDebit
   * @return monthlyDebit
  **/
  @Schema(required = true, description = "")
  public BigDecimal getMonthlyDebit() {
    return monthlyDebit;
  }

  public void setMonthlyDebit(BigDecimal monthlyDebit) {
    this.monthlyDebit = monthlyDebit;
  }

  public DepositLimitsAttributesAchLimits monthlyDebitSoft(BigDecimal monthlyDebitSoft) {
    this.monthlyDebitSoft = monthlyDebitSoft;
    return this;
  }

   /**
   * Get monthlyDebitSoft
   * @return monthlyDebitSoft
  **/
  @Schema(description = "")
  public BigDecimal getMonthlyDebitSoft() {
    return monthlyDebitSoft;
  }

  public void setMonthlyDebitSoft(BigDecimal monthlyDebitSoft) {
    this.monthlyDebitSoft = monthlyDebitSoft;
  }

  public DepositLimitsAttributesAchLimits dailyDebitSoft(BigDecimal dailyDebitSoft) {
    this.dailyDebitSoft = dailyDebitSoft;
    return this;
  }

   /**
   * Get dailyDebitSoft
   * @return dailyDebitSoft
  **/
  @Schema(description = "")
  public BigDecimal getDailyDebitSoft() {
    return dailyDebitSoft;
  }

  public void setDailyDebitSoft(BigDecimal dailyDebitSoft) {
    this.dailyDebitSoft = dailyDebitSoft;
  }

  public DepositLimitsAttributesAchLimits monthlyCredit(BigDecimal monthlyCredit) {
    this.monthlyCredit = monthlyCredit;
    return this;
  }

   /**
   * Get monthlyCredit
   * @return monthlyCredit
  **/
  @Schema(required = true, description = "")
  public BigDecimal getMonthlyCredit() {
    return monthlyCredit;
  }

  public void setMonthlyCredit(BigDecimal monthlyCredit) {
    this.monthlyCredit = monthlyCredit;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DepositLimitsAttributesAchLimits depositLimitsAttributesAchLimits = (DepositLimitsAttributesAchLimits) o;
    return Objects.equals(this.dailyDebit, depositLimitsAttributesAchLimits.dailyDebit) &&
        Objects.equals(this.dailyCredit, depositLimitsAttributesAchLimits.dailyCredit) &&
        Objects.equals(this.monthlyDebit, depositLimitsAttributesAchLimits.monthlyDebit) &&
        Objects.equals(this.monthlyDebitSoft, depositLimitsAttributesAchLimits.monthlyDebitSoft) &&
        Objects.equals(this.dailyDebitSoft, depositLimitsAttributesAchLimits.dailyDebitSoft) &&
        Objects.equals(this.monthlyCredit, depositLimitsAttributesAchLimits.monthlyCredit);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dailyDebit, dailyCredit, monthlyDebit, monthlyDebitSoft, dailyDebitSoft, monthlyCredit);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DepositLimitsAttributesAchLimits {\n");
    
    sb.append("    dailyDebit: ").append(toIndentedString(dailyDebit)).append("\n");
    sb.append("    dailyCredit: ").append(toIndentedString(dailyCredit)).append("\n");
    sb.append("    monthlyDebit: ").append(toIndentedString(monthlyDebit)).append("\n");
    sb.append("    monthlyDebitSoft: ").append(toIndentedString(monthlyDebitSoft)).append("\n");
    sb.append("    dailyDebitSoft: ").append(toIndentedString(dailyDebitSoft)).append("\n");
    sb.append("    monthlyCredit: ").append(toIndentedString(monthlyCredit)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
