/*
 * Unit Python SDK
 * An API for testing openapi-python-client for unit-sdk
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.DepositLimitsAttributesAchLimits;
import io.swagger.client.model.DepositLimitsAttributesAchTotalsDaily;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * DepositLimitsAttributesAch
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-03-26T12:59:56.018830800+03:00[Asia/Jerusalem]")
public class DepositLimitsAttributesAch {
  @SerializedName("limits")
  private DepositLimitsAttributesAchLimits limits = null;

  @SerializedName("totalsDaily")
  private DepositLimitsAttributesAchTotalsDaily totalsDaily = null;

  @SerializedName("totalsMonthly")
  private DepositLimitsAttributesAchTotalsDaily totalsMonthly = null;

  public DepositLimitsAttributesAch limits(DepositLimitsAttributesAchLimits limits) {
    this.limits = limits;
    return this;
  }

   /**
   * Get limits
   * @return limits
  **/
  @Schema(required = true, description = "")
  public DepositLimitsAttributesAchLimits getLimits() {
    return limits;
  }

  public void setLimits(DepositLimitsAttributesAchLimits limits) {
    this.limits = limits;
  }

  public DepositLimitsAttributesAch totalsDaily(DepositLimitsAttributesAchTotalsDaily totalsDaily) {
    this.totalsDaily = totalsDaily;
    return this;
  }

   /**
   * Get totalsDaily
   * @return totalsDaily
  **/
  @Schema(required = true, description = "")
  public DepositLimitsAttributesAchTotalsDaily getTotalsDaily() {
    return totalsDaily;
  }

  public void setTotalsDaily(DepositLimitsAttributesAchTotalsDaily totalsDaily) {
    this.totalsDaily = totalsDaily;
  }

  public DepositLimitsAttributesAch totalsMonthly(DepositLimitsAttributesAchTotalsDaily totalsMonthly) {
    this.totalsMonthly = totalsMonthly;
    return this;
  }

   /**
   * Get totalsMonthly
   * @return totalsMonthly
  **/
  @Schema(required = true, description = "")
  public DepositLimitsAttributesAchTotalsDaily getTotalsMonthly() {
    return totalsMonthly;
  }

  public void setTotalsMonthly(DepositLimitsAttributesAchTotalsDaily totalsMonthly) {
    this.totalsMonthly = totalsMonthly;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DepositLimitsAttributesAch depositLimitsAttributesAch = (DepositLimitsAttributesAch) o;
    return Objects.equals(this.limits, depositLimitsAttributesAch.limits) &&
        Objects.equals(this.totalsDaily, depositLimitsAttributesAch.totalsDaily) &&
        Objects.equals(this.totalsMonthly, depositLimitsAttributesAch.totalsMonthly);
  }

  @Override
  public int hashCode() {
    return Objects.hash(limits, totalsDaily, totalsMonthly);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DepositLimitsAttributesAch {\n");
    
    sb.append("    limits: ").append(toIndentedString(limits)).append("\n");
    sb.append("    totalsDaily: ").append(toIndentedString(totalsDaily)).append("\n");
    sb.append("    totalsMonthly: ").append(toIndentedString(totalsMonthly)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
