/*
 * Unit Python SDK
 * An API for testing openapi-python-client for unit-sdk
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.DepositLimitsAttributesCardLimits;
import io.swagger.client.model.DepositLimitsAttributesCardTotalsDaily;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * DepositLimitsAttributesCard
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-03-26T12:59:56.018830800+03:00[Asia/Jerusalem]")
public class DepositLimitsAttributesCard {
  @SerializedName("limits")
  private DepositLimitsAttributesCardLimits limits = null;

  @SerializedName("totalsDaily")
  private DepositLimitsAttributesCardTotalsDaily totalsDaily = null;

  public DepositLimitsAttributesCard limits(DepositLimitsAttributesCardLimits limits) {
    this.limits = limits;
    return this;
  }

   /**
   * Get limits
   * @return limits
  **/
  @Schema(required = true, description = "")
  public DepositLimitsAttributesCardLimits getLimits() {
    return limits;
  }

  public void setLimits(DepositLimitsAttributesCardLimits limits) {
    this.limits = limits;
  }

  public DepositLimitsAttributesCard totalsDaily(DepositLimitsAttributesCardTotalsDaily totalsDaily) {
    this.totalsDaily = totalsDaily;
    return this;
  }

   /**
   * Get totalsDaily
   * @return totalsDaily
  **/
  @Schema(required = true, description = "")
  public DepositLimitsAttributesCardTotalsDaily getTotalsDaily() {
    return totalsDaily;
  }

  public void setTotalsDaily(DepositLimitsAttributesCardTotalsDaily totalsDaily) {
    this.totalsDaily = totalsDaily;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DepositLimitsAttributesCard depositLimitsAttributesCard = (DepositLimitsAttributesCard) o;
    return Objects.equals(this.limits, depositLimitsAttributesCard.limits) &&
        Objects.equals(this.totalsDaily, depositLimitsAttributesCard.totalsDaily);
  }

  @Override
  public int hashCode() {
    return Objects.hash(limits, totalsDaily);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DepositLimitsAttributesCard {\n");
    
    sb.append("    limits: ").append(toIndentedString(limits)).append("\n");
    sb.append("    totalsDaily: ").append(toIndentedString(totalsDaily)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
