/*
 * Unit Python SDK
 * An API for testing openapi-python-client for unit-sdk
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.math.BigDecimal;
/**
 * DepositLimitsAttributesCheckDepositLimits
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-03-26T12:59:56.018830800+03:00[Asia/Jerusalem]")
public class DepositLimitsAttributesCheckDepositLimits {
  @SerializedName("daily")
  private BigDecimal daily = null;

  @SerializedName("monthly")
  private BigDecimal monthly = null;

  @SerializedName("dailySoft")
  private BigDecimal dailySoft = null;

  @SerializedName("monthlySoft")
  private BigDecimal monthlySoft = null;

  public DepositLimitsAttributesCheckDepositLimits daily(BigDecimal daily) {
    this.daily = daily;
    return this;
  }

   /**
   * Get daily
   * @return daily
  **/
  @Schema(required = true, description = "")
  public BigDecimal getDaily() {
    return daily;
  }

  public void setDaily(BigDecimal daily) {
    this.daily = daily;
  }

  public DepositLimitsAttributesCheckDepositLimits monthly(BigDecimal monthly) {
    this.monthly = monthly;
    return this;
  }

   /**
   * Get monthly
   * @return monthly
  **/
  @Schema(required = true, description = "")
  public BigDecimal getMonthly() {
    return monthly;
  }

  public void setMonthly(BigDecimal monthly) {
    this.monthly = monthly;
  }

  public DepositLimitsAttributesCheckDepositLimits dailySoft(BigDecimal dailySoft) {
    this.dailySoft = dailySoft;
    return this;
  }

   /**
   * Get dailySoft
   * @return dailySoft
  **/
  @Schema(required = true, description = "")
  public BigDecimal getDailySoft() {
    return dailySoft;
  }

  public void setDailySoft(BigDecimal dailySoft) {
    this.dailySoft = dailySoft;
  }

  public DepositLimitsAttributesCheckDepositLimits monthlySoft(BigDecimal monthlySoft) {
    this.monthlySoft = monthlySoft;
    return this;
  }

   /**
   * Get monthlySoft
   * @return monthlySoft
  **/
  @Schema(required = true, description = "")
  public BigDecimal getMonthlySoft() {
    return monthlySoft;
  }

  public void setMonthlySoft(BigDecimal monthlySoft) {
    this.monthlySoft = monthlySoft;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DepositLimitsAttributesCheckDepositLimits depositLimitsAttributesCheckDepositLimits = (DepositLimitsAttributesCheckDepositLimits) o;
    return Objects.equals(this.daily, depositLimitsAttributesCheckDepositLimits.daily) &&
        Objects.equals(this.monthly, depositLimitsAttributesCheckDepositLimits.monthly) &&
        Objects.equals(this.dailySoft, depositLimitsAttributesCheckDepositLimits.dailySoft) &&
        Objects.equals(this.monthlySoft, depositLimitsAttributesCheckDepositLimits.monthlySoft);
  }

  @Override
  public int hashCode() {
    return Objects.hash(daily, monthly, dailySoft, monthlySoft);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DepositLimitsAttributesCheckDepositLimits {\n");
    
    sb.append("    daily: ").append(toIndentedString(daily)).append("\n");
    sb.append("    monthly: ").append(toIndentedString(monthly)).append("\n");
    sb.append("    dailySoft: ").append(toIndentedString(dailySoft)).append("\n");
    sb.append("    monthlySoft: ").append(toIndentedString(monthlySoft)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
