/*
 * Unit Python SDK
 * An API for testing openapi-python-client for unit-sdk
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.Tags;
import io.swagger.client.model.VirtualCardStatus;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import org.threeten.bp.OffsetDateTime;
/**
 * IndividualVirtualDebitCardAttributes
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-03-26T12:59:56.018830800+03:00[Asia/Jerusalem]")
public class IndividualVirtualDebitCardAttributes {
  @SerializedName("createdAt")
  private OffsetDateTime createdAt = null;

  @SerializedName("updatedAt")
  private OffsetDateTime updatedAt = null;

  @SerializedName("last4Digits")
  private String last4Digits = null;

  @SerializedName("expirationDate")
  private String expirationDate = null;

  @SerializedName("bin")
  private String bin = null;

  @SerializedName("status")
  private VirtualCardStatus status = null;

  @SerializedName("tags")
  private Tags tags = null;

  @SerializedName("freezeReason")
  private String freezeReason = null;

  public IndividualVirtualDebitCardAttributes createdAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Get createdAt
   * @return createdAt
  **/
  @Schema(required = true, description = "")
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }

  public IndividualVirtualDebitCardAttributes updatedAt(OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * Get updatedAt
   * @return updatedAt
  **/
  @Schema(description = "")
  public OffsetDateTime getUpdatedAt() {
    return updatedAt;
  }

  public void setUpdatedAt(OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
  }

  public IndividualVirtualDebitCardAttributes last4Digits(String last4Digits) {
    this.last4Digits = last4Digits;
    return this;
  }

   /**
   * Get last4Digits
   * @return last4Digits
  **/
  @Schema(required = true, description = "")
  public String getLast4Digits() {
    return last4Digits;
  }

  public void setLast4Digits(String last4Digits) {
    this.last4Digits = last4Digits;
  }

  public IndividualVirtualDebitCardAttributes expirationDate(String expirationDate) {
    this.expirationDate = expirationDate;
    return this;
  }

   /**
   * Get expirationDate
   * @return expirationDate
  **/
  @Schema(required = true, description = "")
  public String getExpirationDate() {
    return expirationDate;
  }

  public void setExpirationDate(String expirationDate) {
    this.expirationDate = expirationDate;
  }

  public IndividualVirtualDebitCardAttributes bin(String bin) {
    this.bin = bin;
    return this;
  }

   /**
   * Get bin
   * @return bin
  **/
  @Schema(description = "")
  public String getBin() {
    return bin;
  }

  public void setBin(String bin) {
    this.bin = bin;
  }

  public IndividualVirtualDebitCardAttributes status(VirtualCardStatus status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @Schema(required = true, description = "")
  public VirtualCardStatus getStatus() {
    return status;
  }

  public void setStatus(VirtualCardStatus status) {
    this.status = status;
  }

  public IndividualVirtualDebitCardAttributes tags(Tags tags) {
    this.tags = tags;
    return this;
  }

   /**
   * Get tags
   * @return tags
  **/
  @Schema(description = "")
  public Tags getTags() {
    return tags;
  }

  public void setTags(Tags tags) {
    this.tags = tags;
  }

  public IndividualVirtualDebitCardAttributes freezeReason(String freezeReason) {
    this.freezeReason = freezeReason;
    return this;
  }

   /**
   * Get freezeReason
   * @return freezeReason
  **/
  @Schema(description = "")
  public String getFreezeReason() {
    return freezeReason;
  }

  public void setFreezeReason(String freezeReason) {
    this.freezeReason = freezeReason;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IndividualVirtualDebitCardAttributes individualVirtualDebitCardAttributes = (IndividualVirtualDebitCardAttributes) o;
    return Objects.equals(this.createdAt, individualVirtualDebitCardAttributes.createdAt) &&
        Objects.equals(this.updatedAt, individualVirtualDebitCardAttributes.updatedAt) &&
        Objects.equals(this.last4Digits, individualVirtualDebitCardAttributes.last4Digits) &&
        Objects.equals(this.expirationDate, individualVirtualDebitCardAttributes.expirationDate) &&
        Objects.equals(this.bin, individualVirtualDebitCardAttributes.bin) &&
        Objects.equals(this.status, individualVirtualDebitCardAttributes.status) &&
        Objects.equals(this.tags, individualVirtualDebitCardAttributes.tags) &&
        Objects.equals(this.freezeReason, individualVirtualDebitCardAttributes.freezeReason);
  }

  @Override
  public int hashCode() {
    return Objects.hash(createdAt, updatedAt, last4Digits, expirationDate, bin, status, tags, freezeReason);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IndividualVirtualDebitCardAttributes {\n");
    
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    last4Digits: ").append(toIndentedString(last4Digits)).append("\n");
    sb.append("    expirationDate: ").append(toIndentedString(expirationDate)).append("\n");
    sb.append("    bin: ").append(toIndentedString(bin)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("    freezeReason: ").append(toIndentedString(freezeReason)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
