/*
 * Unit Python SDK
 * An API for testing openapi-python-client for unit-sdk
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.Relationships4Account;
import io.swagger.client.model.Relationships5Customer;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Relationships8
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-03-26T12:59:56.018830800+03:00[Asia/Jerusalem]")
public class Relationships8 {
  @SerializedName("account")
  private Relationships4Account account = null;

  @SerializedName("counterpartyAccount")
  private Relationships4Account counterpartyAccount = null;

  @SerializedName("customer")
  private Relationships5Customer customer = null;

  public Relationships8 account(Relationships4Account account) {
    this.account = account;
    return this;
  }

   /**
   * Get account
   * @return account
  **/
  @Schema(description = "")
  public Relationships4Account getAccount() {
    return account;
  }

  public void setAccount(Relationships4Account account) {
    this.account = account;
  }

  public Relationships8 counterpartyAccount(Relationships4Account counterpartyAccount) {
    this.counterpartyAccount = counterpartyAccount;
    return this;
  }

   /**
   * Get counterpartyAccount
   * @return counterpartyAccount
  **/
  @Schema(description = "")
  public Relationships4Account getCounterpartyAccount() {
    return counterpartyAccount;
  }

  public void setCounterpartyAccount(Relationships4Account counterpartyAccount) {
    this.counterpartyAccount = counterpartyAccount;
  }

  public Relationships8 customer(Relationships5Customer customer) {
    this.customer = customer;
    return this;
  }

   /**
   * Get customer
   * @return customer
  **/
  @Schema(description = "")
  public Relationships5Customer getCustomer() {
    return customer;
  }

  public void setCustomer(Relationships5Customer customer) {
    this.customer = customer;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Relationships8 relationships8 = (Relationships8) o;
    return Objects.equals(this.account, relationships8.account) &&
        Objects.equals(this.counterpartyAccount, relationships8.counterpartyAccount) &&
        Objects.equals(this.customer, relationships8.customer);
  }

  @Override
  public int hashCode() {
    return Objects.hash(account, counterpartyAccount, customer);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Relationships8 {\n");
    
    sb.append("    account: ").append(toIndentedString(account)).append("\n");
    sb.append("    counterpartyAccount: ").append(toIndentedString(counterpartyAccount)).append("\n");
    sb.append("    customer: ").append(toIndentedString(customer)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
