/*
 * Unit Python SDK
 * An API for testing openapi-python-client for unit-sdk
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * RequireIdVerification
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-03-26T12:59:56.018830800+03:00[Asia/Jerusalem]")
public class RequireIdVerification {
  @SerializedName("individual")
  private Boolean individual = false;

  @SerializedName("officer")
  private Boolean officer = false;

  @SerializedName("beneficialOwners")
  private Boolean beneficialOwners = false;

  public RequireIdVerification individual(Boolean individual) {
    this.individual = individual;
    return this;
  }

   /**
   * Get individual
   * @return individual
  **/
  @Schema(description = "")
  public Boolean isIndividual() {
    return individual;
  }

  public void setIndividual(Boolean individual) {
    this.individual = individual;
  }

  public RequireIdVerification officer(Boolean officer) {
    this.officer = officer;
    return this;
  }

   /**
   * Get officer
   * @return officer
  **/
  @Schema(description = "")
  public Boolean isOfficer() {
    return officer;
  }

  public void setOfficer(Boolean officer) {
    this.officer = officer;
  }

  public RequireIdVerification beneficialOwners(Boolean beneficialOwners) {
    this.beneficialOwners = beneficialOwners;
    return this;
  }

   /**
   * Get beneficialOwners
   * @return beneficialOwners
  **/
  @Schema(description = "")
  public Boolean isBeneficialOwners() {
    return beneficialOwners;
  }

  public void setBeneficialOwners(Boolean beneficialOwners) {
    this.beneficialOwners = beneficialOwners;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RequireIdVerification requireIdVerification = (RequireIdVerification) o;
    return Objects.equals(this.individual, requireIdVerification.individual) &&
        Objects.equals(this.officer, requireIdVerification.officer) &&
        Objects.equals(this.beneficialOwners, requireIdVerification.beneficialOwners);
  }

  @Override
  public int hashCode() {
    return Objects.hash(individual, officer, beneficialOwners);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RequireIdVerification {\n");
    
    sb.append("    individual: ").append(toIndentedString(individual)).append("\n");
    sb.append("    officer: ").append(toIndentedString(officer)).append("\n");
    sb.append("    beneficialOwners: ").append(toIndentedString(beneficialOwners)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
