/*
 * Unit Python SDK
 * An API for testing openapi-python-client for unit-sdk
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * WirePaymentAttributesImadOmad
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-03-26T12:59:56.018830800+03:00[Asia/Jerusalem]")
public class WirePaymentAttributesImadOmad {
  @SerializedName("imad")
  private String imad = null;

  @SerializedName("omad")
  private String omad = null;

  public WirePaymentAttributesImadOmad imad(String imad) {
    this.imad = imad;
    return this;
  }

   /**
   * Get imad
   * @return imad
  **/
  @Schema(description = "")
  public String getImad() {
    return imad;
  }

  public void setImad(String imad) {
    this.imad = imad;
  }

  public WirePaymentAttributesImadOmad omad(String omad) {
    this.omad = omad;
    return this;
  }

   /**
   * Get omad
   * @return omad
  **/
  @Schema(description = "")
  public String getOmad() {
    return omad;
  }

  public void setOmad(String omad) {
    this.omad = omad;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WirePaymentAttributesImadOmad wirePaymentAttributesImadOmad = (WirePaymentAttributesImadOmad) o;
    return Objects.equals(this.imad, wirePaymentAttributesImadOmad.imad) &&
        Objects.equals(this.omad, wirePaymentAttributesImadOmad.omad);
  }

  @Override
  public int hashCode() {
    return Objects.hash(imad, omad);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WirePaymentAttributesImadOmad {\n");
    
    sb.append("    imad: ").append(toIndentedString(imad)).append("\n");
    sb.append("    omad: ").append(toIndentedString(omad)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
