/*
 * Unit Python SDK
 * An API for testing openapi-python-client for unit-sdk
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.CustomerIdArchiveBody;
import io.swagger.client.model.UnitResponse8;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for ArchiveCustomerApi
 */
@Ignore
public class ArchiveCustomerApiTest {

    private final ArchiveCustomerApi api = new ArchiveCustomerApi();

    /**
     * Archive Customer by Id
     *
     * Archive a Customer via API 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void archiveCustomerByIdTest() throws Exception {
        CustomerIdArchiveBody body = null;
        String customerId = null;
        UnitResponse8 response = api.archiveCustomerById(body, customerId);

        // TODO: test validations
    }
}
