/*
 * Unit Python SDK
 * An API for testing openapi-python-client for unit-sdk
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.RecurringpaymentsBody;
import io.swagger.client.model.UnitResponse13;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for CreateRecurringPaymentApi
 */
@Ignore
public class CreateRecurringPaymentApiTest {

    private final CreateRecurringPaymentApi api = new CreateRecurringPaymentApi();

    /**
     * Create Recurring Payment
     *
     * Create a Recurring Payment via API 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void createRecurringPaymentTest() throws Exception {
        RecurringpaymentsBody body = null;
        UnitResponse13 response = api.createRecurringPayment(body);

        // TODO: test validations
    }
}
