/*
 * Unit Python SDK
 * An API for testing openapi-python-client for unit-sdk
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.UnitResponse6;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for DeactivateControlAgreementForAccountApi
 */
@Ignore
public class DeactivateControlAgreementForAccountApiTest {

    private final DeactivateControlAgreementForAccountApi api = new DeactivateControlAgreementForAccountApi();

    /**
     * Deactivate Account Control Agreement by Id
     *
     * Deactivate Control Agreement for Account via API
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void deactivateDacaAccountByIdTest() throws Exception {
        String accountId = null;
        UnitResponse6 response = api.deactivateDacaAccountById(accountId);

        // TODO: test validations
    }
}
