/*
 * Unit Python SDK
 * An API for testing openapi-python-client for unit-sdk
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for DeleteCounterpartyApi
 */
@Ignore
public class DeleteCounterpartyApiTest {

    private final DeleteCounterpartyApi api = new DeleteCounterpartyApi();

    /**
     * Delete Counterparty by Id
     *
     * Delete Counterparty via API 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void deleteCounterpartyTest() throws Exception {
        String counterpartyId = null;
        api.deleteCounterparty(counterpartyId);

        // TODO: test validations
    }
}
