/*
 * Unit Python SDK
 * An API for testing openapi-python-client for unit-sdk
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.UnitResponse3;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for GetApplicationFormApi
 */
@Ignore
public class GetApplicationFormApiTest {

    private final GetApplicationFormApi api = new GetApplicationFormApi();

    /**
     * Get ApplicationForm by Id
     *
     * Get an Application Form from API 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void findApplicationFormByIdTest() throws Exception {
        String applicationFormId = null;
        String included = null;
        UnitResponse3 response = api.findApplicationFormById(applicationFormId, included);

        // TODO: test validations
    }
}
