/*
 * Unit Python SDK
 * An API for testing openapi-python-client for unit-sdk
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.UnitResponse5;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for GetAccountLimitsApi
 */
@Ignore
public class GetAccountLimitsApiTest {

    private final GetAccountLimitsApi api = new GetAccountLimitsApi();

    /**
     * Get Account Limits by Id
     *
     * Get Account Limits from API 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getAccountLimitsTest() throws Exception {
        String accountId = null;
        UnitResponse5 response = api.getAccountLimits(accountId);

        // TODO: test validations
    }
}
