/*
 * Unit Python SDK
 * An API for testing openapi-python-client for unit-sdk
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.UnitResponse8;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for GetCustomerApi
 */
@Ignore
public class GetCustomerApiTest {

    private final GetCustomerApi api = new GetCustomerApi();

    /**
     * Get Customer by Id
     *
     * Get a Customer from API 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void findCustomerByIdTest() throws Exception {
        String customerId = null;
        UnitResponse8 response = api.findCustomerById(customerId);

        // TODO: test validations
    }
}
