/*
 * Unit Python SDK
 * An API for testing openapi-python-client for unit-sdk
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.Filter2;
import io.swagger.client.model.ListPageParametersObject;
import io.swagger.client.model.UnitResponseAccountsList;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for GetListAccountsApi
 */
@Ignore
public class GetListAccountsApiTest {

    private final GetListAccountsApi api = new GetListAccountsApi();

    /**
     * Get List Accounts
     *
     * Get List Accounts from API 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void findListAccountsTest() throws Exception {
        ListPageParametersObject page = null;
        Filter2 filter = null;
        UnitResponseAccountsList response = api.findListAccounts(page, filter);

        // TODO: test validations
    }
}
