/*
 * Unit Python SDK
 * An API for testing openapi-python-client for unit-sdk
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.Filter12;
import io.swagger.client.model.ListPageParametersObject;
import io.swagger.client.model.Transaction;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for GetListTransactionsApi
 */
@Ignore
public class GetListTransactionsApiTest {

    private final GetListTransactionsApi api = new GetListTransactionsApi();

    /**
     * Get List Transactions
     *
     * Get List Transactions from API 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void findListTransactionsTest() throws Exception {
        ListPageParametersObject page = null;
        Filter12 filter = null;
        String sort = null;
        List<Transaction> response = api.findListTransactions(page, filter, sort);

        // TODO: test validations
    }
}
