/*
 * Unit Python SDK
 * An API for testing openapi-python-client for unit-sdk
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.UnitResponse8;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for GetListCustomersApi
 */
@Ignore
public class GetListCustomersApiTest {

    private final GetListCustomersApi api = new GetListCustomersApi();

    /**
     * Get Customers List
     *
     * Get Customers List from API 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getCustomersListTest() throws Exception {
        UnitResponse8 response = api.getCustomersList();

        // TODO: test validations
    }
}
