/*
 * Unit Python SDK
 * An API for testing openapi-python-client for unit-sdk
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.Authorization;
import io.swagger.client.model.Filter5;
import io.swagger.client.model.ListPageParametersObject;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for GetListAuthorizationsApi
 */
@Ignore
public class GetListAuthorizationsApiTest {

    private final GetListAuthorizationsApi api = new GetListAuthorizationsApi();

    /**
     * Get List authorizations
     *
     * Get List Authorizations from API 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void findListAuthorizationsTest() throws Exception {
        ListPageParametersObject page = null;
        Filter5 filter = null;
        String sort = null;
        List<Authorization> response = api.findListAuthorizations(page, filter, sort);

        // TODO: test validations
    }
}
