/*
 * Unit Python SDK
 * An API for testing openapi-python-client for unit-sdk
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.Filter7;
import io.swagger.client.model.ListPageParametersObject;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for GetListStatementsApi
 */
@Ignore
public class GetListStatementsApiTest {

    private final GetListStatementsApi api = new GetListStatementsApi();

    /**
     * Get List Statements
     *
     * Get List Statements from API 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void findListStatementsTest() throws Exception {
        ListPageParametersObject page = null;
        Filter7 filter = null;
        String sort = null;
        List<Object> response = api.findListStatements(page, filter, sort);

        // TODO: test validations
    }
}
