/*
 * Unit Python SDK
 * An API for testing openapi-python-client for unit-sdk
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.AuthorizationRequest;
import io.swagger.client.model.Filter6;
import io.swagger.client.model.ListPageParametersObject;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for GetListAuthorizationRequestsApi
 */
@Ignore
public class GetListAuthorizationRequestsApiTest {

    private final GetListAuthorizationRequestsApi api = new GetListAuthorizationRequestsApi();

    /**
     * Get List Authorization Requests
     *
     * Get List Authorization Requests from API 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void findListAuthorizationRequestsTest() throws Exception {
        ListPageParametersObject page = null;
        Filter6 filter = null;
        String sort = null;
        List<AuthorizationRequest> response = api.findListAuthorizationRequests(page, filter, sort);

        // TODO: test validations
    }
}
