/*
 * Unit Python SDK
 * An API for testing openapi-python-client for unit-sdk
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.Filter3;
import io.swagger.client.model.InlineResponse200;
import io.swagger.client.model.ListPageParametersObject;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for GetListPaymentsApi
 */
@Ignore
public class GetListPaymentsApiTest {

    private final GetListPaymentsApi api = new GetListPaymentsApi();

    /**
     * Get List Payments
     *
     * Get List Payments from API 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getListPaymentsTest() throws Exception {
        ListPageParametersObject page = null;
        Filter3 filter = null;
        InlineResponse200 response = api.getListPayments(page, filter);

        // TODO: test validations
    }
}
