/*
 * Unit Python SDK
 * An API for testing openapi-python-client for unit-sdk
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.UnitResponse13;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for GetRecurringPaymentApi
 */
@Ignore
public class GetRecurringPaymentApiTest {

    private final GetRecurringPaymentApi api = new GetRecurringPaymentApi();

    /**
     * Get Recurring Payment
     *
     * Get Recurring Payment from API 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getRecurringPaymentTest() throws Exception {
        String paymentId = null;
        UnitResponse13 response = api.getRecurringPayment(paymentId);

        // TODO: test validations
    }
}
