/*
 * Unit Python SDK
 * An API for testing openapi-python-client for unit-sdk
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.UnitResponse29;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for GetTransactionApi
 */
@Ignore
public class GetTransactionApiTest {

    private final GetTransactionApi api = new GetTransactionApi();

    /**
     * Get Transaction by Id
     *
     * Get a Transaction from API 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void findTransactionIdTest() throws Exception {
        String accountId = null;
        String transactionId = null;
        UnitResponse29 response = api.findTransactionId(accountId, transactionId);

        // TODO: test validations
    }
}
