/*
 * Unit Python SDK
 * An API for testing openapi-python-client for unit-sdk
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.UnitResponse29;
import io.swagger.client.model.UpdateUnitRequest;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for UpdateTransactionApi
 */
@Ignore
public class UpdateTransactionApiTest {

    private final UpdateTransactionApi api = new UpdateTransactionApi();

    /**
     * Update Transaction
     *
     * Update a Transaction via API 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void updateTransactionTest() throws Exception {
        UpdateUnitRequest body = null;
        String accountId = null;
        String transactionId = null;
        UnitResponse29 response = api.updateTransaction(body, accountId, transactionId);

        // TODO: test validations
    }
}
